# -*- sh -*- # for font lock mode
# variable definitions
- env = export SCRAM_ARCH=slc7_amd64_gcc700; eval `scramv1 project CMSSW CMSSW_10_2_9` ; cp -r tardir/PhysicsTools CMSSW_10_2_9/src ; cd CMSSW_10_2_9/src ; eval `scram b` ;eval `scramv1 runtime -sh`; eval `scram b` ; cd -
- tag = 
- output = outputFile=
- tagmode = none
- tarfile = /afs/cern.ch/work/k/knash/NanoAODskim/NanoAODskim_Analyzer/CMSSW_10_2_9/src/tarball.tgz
- untardir = tardir
- copycommand = cp

# Sections listed
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp1500Nar_Bp800Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp1500Nar_Tp800Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp1500Nar_Bp1000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp1500Nar_Tp1000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp1500Nar_Bp1300Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp1500Nar_Tp1300Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp2000Nar_Bp1000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp2000Nar_Tp1000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp2000Nar_Bp1300Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp2000Nar_Tp1300Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp2000Nar_Bp1700Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp2000Nar_Tp1700Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp2500Nar_Bp1300Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp2500Nar_Tp1300Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp2500Nar_Bp1700Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp2500Nar_Tp1700Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp2500Nar_Bp2000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp2500Nar_Tp2000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp3000Nar_Bp1700Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp3000Nar_Tp1700Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp3000Nar_Bp2000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp3000Nar_Tp2000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp3000Nar_Bp2300Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp3000Nar_Tp2300Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp3500Nar_Bp1700Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp3500Nar_Tp1700Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp3500Nar_Bp2000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp3500Nar_Tp2000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp3500Nar_Bp2300Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp3500Nar_Tp2300Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp3500Nar_Bp2700Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp3500Nar_Tp2700Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp3500Nar_Bp3000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp3500Nar_Tp3000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp4000Nar_Bp2000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp4000Nar_Tp2000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp4000Nar_Bp2300Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp4000Nar_Tp2300Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp4000Nar_Bp2700Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp4000Nar_Tp2700Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp4000Nar_Bp3000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp4000Nar_Tp3000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp4000Nar_Bp3300Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp4000Nar_Tp3300Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp4500Nar_Bp2300Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp4500Nar_Tp2300Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp4500Nar_Bp2700Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp4500Nar_Tp2700Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp4500Nar_Bp3000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp4500Nar_Tp3000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp4500Nar_Bp3300Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp4500Nar_Tp3300Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp4500Nar_Bp3700Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp4500Nar_Tp3700Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp5000Nar_Bp2700Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp5000Nar_Tp2700Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp5000Nar_Bp3000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp5000Nar_Tp3000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp5000Nar_Bp3300Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp5000Nar_Tp3300Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp5000Nar_Bp3700Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp5000Nar_Tp3700Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp5000Nar_Bp4000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp5000Nar_Tp4000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp5500Nar_Bp3000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp5500Nar_Tp3000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp5500Nar_Bp3300Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp5500Nar_Tp3300Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp5500Nar_Bp3700Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp5500Nar_Tp3700Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp5500Nar_Bp4000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp5500Nar_Tp4000Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToBpT_Wp5500Nar_Bp4400Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  WpToTpB_Wp5500Nar_Tp4400Nar_Ht_TuneCP5_13TeV-madgraphMLM-pythia8  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash -v v8,v10 --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 1 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 2 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 3 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 4 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 5 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 6 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 7 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 8 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 9 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 10 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 11 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 12 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 13 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 14 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 15 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 16 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 17 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 18 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 19 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 20 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 21 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 22 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 23 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 24 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 25 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt   --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 1 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 2 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 3 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 4 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 5 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 6 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 7 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 8 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 9 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 10 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 11 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 12 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 13 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 14 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 15 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 16 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 17 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 18 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 19 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 20 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 21 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 22 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 23 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 24 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 25 -t 25  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 1 -t 15  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 2 -t 15  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 3 -t 15  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 4 -t 15  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 5 -t 15  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 6 -t 15  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 7 -t 15  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 8 -t 15  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 9 -t 15  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 10 -t 15  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 11 -t 15  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 12 -t 15  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 13 -t 15  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 14 -t 15  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 -j 15 -t 15  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash --cutopt    --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-700to1000_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 1 -t 5  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-700to1000_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 2 -t 5  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-700to1000_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 3 -t 5  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-700to1000_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 4 -t 5  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-700to1000_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 5 -t 5  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 1 -t 20  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 2 -t 20  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 3 -t 20  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 4 -t 20  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 5 -t 20  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 6 -t 20  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 7 -t 20  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 8 -t 20  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 9 -t 20  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 10 -t 20  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 11 -t 20  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 12 -t 20  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 13 -t 20  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 14 -t 20  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 15 -t 20  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 16 -t 20  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 17 -t 20  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 18 -t 20  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 19 -t 20  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor
output_$(JID)        python ./tardir/NanoAODskim_Generic.py -a tHb -s  TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8 -j 20 -t 20  --Ana -e 2016 -f /eos/cms/store/group/phys_b2g/knash   --cutopt  --condor

