hadd NanoAODskim_optimizer_tHbAna2016__QCD.root NanoAODskim_optimizer_tHbAna2016__QCD*.root ; hadd NanoAODskim_optimizer_tHbAna2016__TT.root NanoAODskim_optimizer_tHbAna2016__TT*.root
mv NanoAODskim_optimizer_tHbAna2016__QCD.root NanoAODskim_optimizer_tHbAna2016__TT.root NanoAODskim_optimizer_tHbAna2016__WpTo*.root rootfiles/

hadd NanoAODskim_optimizer_tHbAna2017__QCD.root NanoAODskim_optimizer_tHbAna2017__QCD*.root ; hadd NanoAODskim_optimizer_tHbAna2017__TT.root NanoAODskim_optimizer_tHbAna2017__TT*.root
mv NanoAODskim_optimizer_tHbAna2017__QCD.root NanoAODskim_optimizer_tHbAna2017__TT.root NanoAODskim_optimizer_tHbAna2017__WpTo*.root rootfiles/

hadd NanoAODskim_optimizer_tHbAna2018__QCD.root NanoAODskim_optimizer_tHbAna2018__QCD*.root ; hadd NanoAODskim_optimizer_tHbAna2018__TT.root NanoAODskim_optimizer_tHbAna2018__TT*.root
mv NanoAODskim_optimizer_tHbAna2018__QCD.root NanoAODskim_optimizer_tHbAna2018__TT.root NanoAODskim_optimizer_tHbAna2018__WpTo*.root rootfiles/

mv NanoAODskim_optimizer_tHb*.root rootfiles_tosum/
